dicionario = {1 : {'nome' : 'Maria' , 'idade' : 26 , 'nacionalidade' : 'brasileira'}}
dicionario.update({'religiao' : 'catolica' , 'cor' : 'parda', 'filhos' : 2})
print(dicionario)
copia = dicionario.copy()
print(copia)
dicionario.pop(1)
print(dicionario)
print(copia)
filhos = dicionario.popitem()
print(dicionario)
dicionario.clear()
copia.clear()
print(dicionario)
print(copia)
x = ('nome', 'idade', 'nacionalidade')
y = ('A preencher')
novo_dicionario = dict.fromkeys(x,y)
print(novo_dicionario)
print(novo_dicionario.items())
print(novo_dicionario.keys())
print(novo_dicionario.values())
