set_inicial = {11, 12, 13, 14}
print(f"Set_inicial é {set_inicial}")
set_inicial.add(15)
print(f"Set_inicial.add é {set_inicial}")
x = (1,2,3,4,5)
set_inicial.update(x)
print(f"set_inicial.update é {set_inicial}")
set_inicial.discard(13)
print(f"set_inicial.discard é {set_inicial}")
novo_set = {20,21,23,1,2}
print(f"novo_set é {novo_set}")
uniao = set_inicial.union(novo_set)
print(f"novo_set.union é {uniao}")
intersecao = set_inicial.intersection(novo_set)
print(f"novo_set.intersecao é {intersecao}")
diferenca = set_inicial.difference(novo_set)
print(f"novo_set.diferenca é {diferenca}")
diferenca_simetrica = set_inicial.symmetric_difference(novo_set)
print(f"novo_set.symmetric_difference é {diferenca_simetrica}")